"use client";

import Link from "next/link";
import { useState } from "react";
import { useStore } from "@/components/StoreProvider";
import { MediaPlaceholder } from "@/components/MediaPlaceholder";
import { calculateTotals, evaluateCoupon, formatINR } from "@/lib/commerce";

export default function CartPage() {
  const { cart, coupon, settings, setCoupon, removeFromCart, updateQuantity, toggleWishlist, clearCart, notify } = useStore();
  const [code, setCode] = useState(coupon?.code || ""); const [message, setMessage] = useState(coupon?.message || ""); const [error, setError] = useState(""); const [giftCode, setGiftCode] = useState(""); const [giftMessage, setGiftMessage] = useState("");
  const totals = calculateTotals(cart, coupon, "cod", settings);
  const apply = () => { try { const result = evaluateCoupon(code, totals.subtotal); setCoupon(result); setMessage(result.message); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Coupon could not be applied."); setMessage(""); } };
  if (!cart.length) return <div className="empty-state standalone"><span>Your bag · 0</span><h1>Nothing is folded here yet.</h1><p>Find a piece that feels like your next story.</p><Link className="button button-dark" href="/shop">Explore the collection</Link><Link href="/wishlist">Open your wishlist</Link></div>;
  return <div className="cart-page"><header className="utility-hero"><p>Your bag</p><h1>Pieces chosen<br /><em>with feeling.</em></h1><span>{cart.reduce((sum, line) => sum + line.quantity, 0)} demo items</span></header><div className="cart-layout"><section className="cart-lines"><div className="cart-lines-header"><span>Your selection</span><button onClick={clearCart}>Clear bag</button></div>{cart.map((line) => <article className="cart-line" key={line.key}><Link href={`/product/${line.slug}`}><MediaPlaceholder src={line.image} alt={line.name} /></Link><div><p>{line.category}</p><Link href={`/product/${line.slug}`}><h2>{line.name}</h2></Link><span>Size: {line.size}</span><div className="line-actions"><div className="quantity"><button onClick={() => updateQuantity(line.key, line.quantity - 1)}>−</button><span>{line.quantity}</span><button onClick={() => updateQuantity(line.key, line.quantity + 1)}>+</button></div><button onClick={() => { toggleWishlist(line.productId); removeFromCart(line.key); notify("Moved to your wishlist."); }}>Save for later</button><button onClick={() => removeFromCart(line.key)}>Remove</button></div></div><strong>{formatINR(line.unitPrice * line.quantity)}</strong></article>)}</section><aside className="order-summary"><h2>Order summary</h2><div className="coupon-box"><label htmlFor="coupon">Demo coupon</label><div><input id="coupon" value={code} onChange={(event) => setCode(event.target.value)} placeholder="KADHAI10" /><button onClick={apply}>Apply</button></div>{message && <p className="success-text">{message}</p>}{error && <p className="error-text">{error}</p>}<small>Try KADHAI10 or WELCOME500</small></div><div className="coupon-box gift-card-box"><label htmlFor="gift-card">Demo gift card</label><div><input id="gift-card" value={giftCode} onChange={(event) => setGiftCode(event.target.value)} placeholder="THREADS1000" /><button onClick={() => setGiftMessage(giftCode.trim().toUpperCase() === "THREADS1000" ? "Demo gift card recognised. It has no real monetary value." : "Try the seeded code THREADS1000.")}>Check</button></div>{giftMessage && <p className={giftCode.trim().toUpperCase() === "THREADS1000" ? "success-text" : "error-text"}>{giftMessage}</p>}</div><dl><div><dt>Subtotal</dt><dd>{formatINR(totals.subtotal)}</dd></div>{totals.discount > 0 && <div className="discount"><dt>Discount</dt><dd>− {formatINR(totals.discount)}</dd></div>}<div><dt>Demo shipping</dt><dd>{totals.shipping ? formatINR(totals.shipping) : "Complimentary"}</dd></div><div className="total"><dt>Estimated total</dt><dd>{formatINR(totals.total)}</dd></div></dl><Link className="button button-dark full-button" href="/checkout">Continue to demo checkout</Link><p className="prototype-note">No payment is processed. Taxes, delivery, gift values, and fees shown are demonstration values.</p></aside></div></div>;
}
