"use client";

import { Suspense, useState } from "react";
import { useSearchParams } from "next/navigation";
import { useStore } from "@/components/StoreProvider";

const stages = ["Order placed", "Preparing your piece", "Packed", "Out for delivery", "Delivered"];
function Tracker() { const params = useSearchParams(); const { orders } = useStore(); const [value, setValue] = useState(params.get("order") || ""); const [searched, setSearched] = useState(Boolean(params.get("order"))); const order = orders.find((item) => item.id.toLowerCase() === value.trim().toLowerCase() || item.phone === value.trim()) || (!orders.length && value === "KDH-2026-1042" ? { id: "KDH-2026-1042", status: "Packed", customer: "Demo guest", phone: "", address: "Jaipur, Rajasthan", items: [], total: 12500, payment: "cod", createdAt: "" } : null); const active = order ? Math.max(0, stages.indexOf(order.status)) : 0; return <div className="track-page"><header className="utility-hero"><p>Track a prototype order</p><h1>Follow every<br /><em>fold.</em></h1><span>Try KDH-2026-1042</span></header><form onSubmit={(event) => { event.preventDefault(); setSearched(true); }}><label htmlFor="tracking">Demo order number or mobile number</label><div><input id="tracking" value={value} onChange={(event) => setValue(event.target.value)} placeholder="KDH-2026-1042" /><button className="button button-dark">Find order</button></div><p>No courier service is contacted. Statuses are stored only in this prototype.</p></form>{searched && (order ? <section className="tracking-result"><div className="tracking-head"><div><span>Prototype order</span><h2>{order.id}</h2></div><div><span>Current status</span><strong>{order.status}</strong></div><div><span>Demo estimate</span><strong>4–6 business days</strong></div></div><ol>{stages.map((stage, index) => <li className={index <= active ? "is-complete" : ""} key={stage}><i>{index < active ? "✓" : index + 1}</i><div><strong>{stage}</strong><span>{index === active ? "Current demo status" : index < active ? "Completed in simulation" : "Not started"}</span></div></li>)}</ol></section> : <div className="empty-state compact"><span>No match</span><h2>That demo order was not found.</h2><p>Try KDH-2026-1042 or use an order created on this device.</p></div>)}</div>; }
export default function TrackOrderPage() { return <Suspense fallback={<div className="page-loading">Finding the thread…</div>}><Tracker /></Suspense>; }
