"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { products } from "@/data/products";
import { formatINR } from "@/lib/commerce";
import { useStore } from "./StoreProvider";

const nav = [["Overview", "/admin"], ["Products", "/admin/products"], ["Orders", "/admin/orders"], ["Homepage content", "/admin/content"], ["Coupons", "/admin/coupons"], ["Settings", "/admin/settings"]];
const statuses = ["Order placed", "Preparing your piece", "Packed", "Out for delivery", "Delivered"];

export function AdminPanel() {
  const pathname = usePathname(); const { orders, content, settings, stockOverrides, updateOrderStatus, updateContent, updateSettings, updateStock, notify } = useStore();
  const [query, setQuery] = useState(""); const [contentDraft, setContentDraft] = useState(content); const [settingsDraft, setSettingsDraft] = useState(settings); const [couponState, setCouponState] = useState({ KADHAI10: true, WELCOME500: true });
  const view = pathname.split("/")[2] || "overview"; const displayOrders = orders.length ? orders : [{ id: "KDH-2026-1042", createdAt: new Date().toISOString(), customer: "Demo Guest", phone: "9999999999", address: "Jaipur, Rajasthan", items: [], total: 12500, payment: "cod", status: "Packed" }];
  const filteredProducts = products.filter((item) => item.name.toLowerCase().includes(query.toLowerCase()) || item.sku.toLowerCase().includes(query.toLowerCase()));

  const title = view === "overview" ? "Good morning, Kadhai." : view === "content" ? "Homepage content" : view.charAt(0).toUpperCase() + view.slice(1);
  return <div className="admin-shell"><aside className="admin-sidebar"><Link href="/" className="admin-logo">Kadhai<small>Studio</small></Link><nav>{nav.map(([label, href]) => <Link className={pathname === href ? "is-active" : ""} href={href} key={href}>{label}</Link>)}</nav><div><span>Prototype mode</span><p>No authentication enabled</p><Link href="/">← View storefront</Link></div></aside><section className="admin-content"><div className="admin-warning">Demo admin — changes stay in this browser only. No authentication is enabled.</div><header className="admin-header"><div><p>{new Date().toLocaleDateString("en-IN", { weekday: "long", day: "numeric", month: "long" })}</p><h1>{title}</h1></div><button onClick={() => notify("No notifications in this prototype.")}>Notifications · 0</button></header>
    {view === "overview" && <><div className="admin-metrics"><article><span>Demo revenue</span><strong>{formatINR(displayOrders.reduce((sum, order) => sum + order.total, 0))}</strong><small>Local prototype orders</small></article><article><span>Orders</span><strong>{displayOrders.length}</strong><small>1 requires attention</small></article><article><span>Catalog pieces</span><strong>{products.length}</strong><small>Across 4 clothing categories</small></article><article><span>Low stock</span><strong>{products.filter((item) => (stockOverrides[item.id] ?? item.stock) <= 4).length}</strong><small>Demo inventory</small></article></div><div className="admin-columns"><section className="admin-card"><header><h2>Recent orders</h2><Link href="/admin/orders">View all</Link></header>{displayOrders.slice(0, 4).map((order) => <div className="mini-order" key={order.id}><span>{order.id}</span><p>{order.customer}</p><b>{formatINR(order.total)}</b><i>{order.status}</i></div>)}</section><section className="admin-card"><header><h2>Top categories</h2></header>{[["Sarees", 55], ["Ready sarees", 18], ["Lehengas", 14], ["Salwar suits", 13]].map(([name, value]) => <div className="category-bar" key={name}><span>{name}</span><i><b style={{ width: `${value}%` }} /></i><strong>{value}%</strong></div>)}</section></div></>}
    {view === "products" && <section className="admin-card admin-table-card"><div className="admin-tools"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search products or SKU" /><button onClick={() => notify("Create product is a visual prototype action.")}>+ Create product</button></div><div className="admin-table"><div className="admin-table-head"><span>Product</span><span>Category</span><span>Price</span><span>Stock</span><span>Status</span><span>Action</span></div>{filteredProducts.map((item) => <div className="admin-table-row" key={item.id}><span><i>{item.name.slice(0, 1)}</i><b>{item.name}<small>{item.sku}</small></b></span><span>{item.category}</span><span>{formatINR(item.price)}</span><span><input type="number" min="0" value={stockOverrides[item.id] ?? item.stock} onChange={(event) => updateStock(item.id, Number(event.target.value))} /></span><span className={(stockOverrides[item.id] ?? item.stock) <= 4 ? "low-stock" : "in-stock"}>{(stockOverrides[item.id] ?? item.stock) <= 4 ? "Low stock" : "Active"}</span><span><button onClick={() => notify(`${item.name} edit opened in demo mode.`)}>Edit</button><button onClick={() => notify("Delete is intentionally simulated; no product was removed.")}>•••</button></span></div>)}</div></section>}
    {view === "orders" && <section className="admin-card admin-table-card"><div className="admin-tools"><h2>Prototype orders</h2><button onClick={() => notify("Demo order list refreshed.")}>Refresh</button></div><div className="admin-table orders-table"><div className="admin-table-head"><span>Order</span><span>Customer</span><span>Total</span><span>Payment</span><span>Status</span></div>{displayOrders.map((order) => <div className="admin-table-row" key={order.id}><span><b>{order.id}<small>{new Date(order.createdAt).toLocaleDateString("en-IN")}</small></b></span><span>{order.customer}</span><span>{formatINR(order.total)}</span><span>{order.payment === "cod" ? "Demo COD" : "Demo online"}</span><span><select value={order.status} onChange={(event) => orders.length ? updateOrderStatus(order.id, event.target.value) : notify("Create a storefront order to edit its live demo status.")}>{statuses.map((status) => <option key={status}>{status}</option>)}</select></span></div>)}</div></section>}
    {view === "content" && <form className="admin-form admin-card" onSubmit={(event) => { event.preventDefault(); updateContent(contentDraft); }}><p>Changes update the public homepage immediately.</p><label>Announcement strip<input value={contentDraft.announcement} onChange={(event) => setContentDraft({ ...contentDraft, announcement: event.target.value })} /></label><label>Hero headline<input value={contentDraft.heroHeadline} onChange={(event) => setContentDraft({ ...contentDraft, heroHeadline: event.target.value })} /></label><label>Hero supporting copy<textarea rows={3} value={contentDraft.heroSupport} onChange={(event) => setContentDraft({ ...contentDraft, heroSupport: event.target.value })} /></label><label>Campaign copy<textarea rows={4} value={contentDraft.campaignCopy} onChange={(event) => setContentDraft({ ...contentDraft, campaignCopy: event.target.value })} /></label><fieldset className="featured-picker"><legend>Featured homepage products · choose up to 8</legend><div>{products.map((item) => <label key={item.id}><input type="checkbox" checked={contentDraft.featuredProductIds.includes(item.id)} onChange={(event) => { const ids = event.target.checked ? [...contentDraft.featuredProductIds, item.id].slice(-8) : contentDraft.featuredProductIds.filter((id) => id !== item.id); setContentDraft({ ...contentDraft, featuredProductIds: ids }); }} />{item.name}</label>)}</div><small>{contentDraft.featuredProductIds.length} selected. Saving updates the public homepage grid.</small></fieldset><button className="button button-dark">Save homepage content</button></form>}
    {view === "coupons" && <section className="admin-card coupon-admin"><p>Seeded demo codes</p>{[["KADHAI10", "10% off · capped at ₹2,000"], ["WELCOME500", "₹500 off · minimum ₹5,000"]].map(([code, detail]) => <article key={code}><div><strong>{code}</strong><span>{detail}</span></div><button className={couponState[code as keyof typeof couponState] ? "is-on" : ""} onClick={() => setCouponState({ ...couponState, [code]: !couponState[code as keyof typeof couponState] })}><i />{couponState[code as keyof typeof couponState] ? "Active" : "Inactive"}</button></article>)}<article><div><strong>THREADS1000</strong><span>Demo gift card success state</span></div><button className="is-on"><i />Active</button></article><small>Coupon toggles are visual admin controls in this prototype; seeded checkout logic remains available for demonstrations.</small></section>}
    {view === "settings" && <form className="admin-form admin-card" onSubmit={(event) => { event.preventDefault(); updateSettings(settingsDraft); }}><p>Prototype commerce settings</p><div className="admin-form-grid"><label>Shipping fee (₹)<input type="number" value={settingsDraft.shippingFee} onChange={(event) => setSettingsDraft({ ...settingsDraft, shippingFee: Number(event.target.value) })} /></label><label>Free shipping above (₹)<input type="number" value={settingsDraft.freeShipping} onChange={(event) => setSettingsDraft({ ...settingsDraft, freeShipping: Number(event.target.value) })} /></label><label>COD demo fee (₹)<input type="number" value={settingsDraft.codFee} onChange={(event) => setSettingsDraft({ ...settingsDraft, codFee: Number(event.target.value) })} /></label></div><label>Delivery copy<input value={settingsDraft.deliveryCopy} onChange={(event) => setSettingsDraft({ ...settingsDraft, deliveryCopy: event.target.value })} /></label><button className="button button-dark">Save demo settings</button></form>}
  </section></div>;
}
